apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-gr6x
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0017-tenant/tkrw-pr712-0075-0017-app/devfile-sample-gr6x@sha256:490f0928489ee98618dfe789e5a22dba7c8c6d405b97bca96a28f5399e9145e1
        name: my-nodejs
        resources: {}
status: {}
